//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NexxtSchedule.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Item.
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        public static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprar.
        /// </summary>
        public static string ButtonBuy {
            get {
                return ResourceManager.GetString("ButtonBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string ButtonDetail {
            get {
                return ResourceManager.GetString("ButtonDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string ButtonEntrar {
            get {
                return ResourceManager.GetString("ButtonEntrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string ButtonNew {
            get {
                return ResourceManager.GetString("ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        public static string ButtonPrint {
            get {
                return ResourceManager.GetString("ButtonPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte.
        /// </summary>
        public static string ButtonReport {
            get {
                return ResourceManager.GetString("ButtonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string Client_IndeView_titulo1 {
            get {
                return ResourceManager.GetString("Client_IndeView_titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion.
        /// </summary>
        public static string Client_Model_Address {
            get {
                return ResourceManager.GetString("Client_Model_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Client_Model_Cliente {
            get {
                return ResourceManager.GetString("Client_Model_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compania.
        /// </summary>
        public static string Client_Model_Compania {
            get {
                return ResourceManager.GetString("Client_Model_Compania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string Client_Model_LastName {
            get {
                return ResourceManager.GetString("Client_Model_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movil.
        /// </summary>
        public static string Client_Model_Movil {
            get {
                return ResourceManager.GetString("Client_Model_Movil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacimiento.
        /// </summary>
        public static string Client_Model_Nacimiento {
            get {
                return ResourceManager.GetString("Client_Model_Nacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Client_Model_Name {
            get {
                return ResourceManager.GetString("Client_Model_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero Documento.
        /// </summary>
        public static string Client_Model_NumeroDocu {
            get {
                return ResourceManager.GetString("Client_Model_NumeroDocu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string Client_Model_Phone {
            get {
                return ResourceManager.GetString("Client_Model_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Documento.
        /// </summary>
        public static string Client_Model_TipoDocu {
            get {
                return ResourceManager.GetString("Client_Model_TipoDocu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string Client_Model_UserName {
            get {
                return ResourceManager.GetString("Client_Model_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color_Model_ColorDate {
            get {
                return ResourceManager.GetString("Color_Model_ColorDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Seleccione Item...].
        /// </summary>
        public static string ComboSelect {
            get {
                return ResourceManager.GetString("ComboSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Company_Model_Active {
            get {
                return ResourceManager.GetString("Company_Model_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion.
        /// </summary>
        public static string Company_Model_Address {
            get {
                return ResourceManager.GetString("Company_Model_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anulado.
        /// </summary>
        public static string Company_Model_Anulado {
            get {
                return ResourceManager.GetString("Company_Model_Anulado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string Company_Model_Compania {
            get {
                return ResourceManager.GetString("Company_Model_Compania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pais.
        /// </summary>
        public static string Company_Model_Country {
            get {
                return ResourceManager.GetString("Company_Model_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde.
        /// </summary>
        public static string Company_Model_Desde {
            get {
                return ResourceManager.GetString("Company_Model_Desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta.
        /// </summary>
        public static string Company_Model_Hasta {
            get {
                return ResourceManager.GetString("Company_Model_Hasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Company_Model_Logo {
            get {
                return ResourceManager.GetString("Company_Model_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string Company_Model_Phone {
            get {
                return ResourceManager.GetString("Company_Model_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string Company_Model_Precio {
            get {
                return ResourceManager.GetString("Company_Model_Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nit / CI.
        /// </summary>
        public static string Company_Model_Rif {
            get {
                return ResourceManager.GetString("Company_Model_Rif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string Company_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Company_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pais.
        /// </summary>
        public static string Country_Model_Pais {
            get {
                return ResourceManager.GetString("Country_Model_Pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pais.
        /// </summary>
        public static string Country_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Country_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string DirectGeneral_Model_Cantidad {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string DirectGeneral_Model_Cliente {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string DirectGeneral_Model_Company {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero Pago.
        /// </summary>
        public static string DirectGeneral_Model_ComprobantePago {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_ComprobantePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string DirectGeneral_Model_Date {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago Directo.
        /// </summary>
        public static string DIrectGeneral_Model_DirectPayment {
            get {
                return ResourceManager.GetString("DIrectGeneral_Model_DirectPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturado.
        /// </summary>
        public static string DirectGeneral_Model_Facturado {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_Facturado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Facturado.
        /// </summary>
        public static string DirectGeneral_Model_FechaFacturado {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_FechaFacturado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota Cobro.
        /// </summary>
        public static string DirectGeneral_Model_NotaCobro {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_NotaCobro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string DirectGeneral_Model_Precio {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentaje.
        /// </summary>
        public static string DirectGeneral_Model_ProcentajeProfesional {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_ProcentajeProfesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesional.
        /// </summary>
        public static string DirectGeneral_Model_Profesional {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_Profesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio.
        /// </summary>
        public static string DirectGeneral_Model_Servicio {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_Servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasa Profesional.
        /// </summary>
        public static string DirectGeneral_Model_TasaProfesional {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_TasaProfesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        public static string DirectGeneral_Model_Tax {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string DirectGeneral_Model_Total {
            get {
                return ResourceManager.GetString("DirectGeneral_Model_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagos Pendientes.
        /// </summary>
        public static string DirectGeneral_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("DirectGeneral_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobro Directo.
        /// </summary>
        public static string DirectPayment_IndexView_Titulo1 {
            get {
                return ResourceManager.GetString("DirectPayment_IndexView_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string DirectPayment_Model_Cantidad {
            get {
                return ResourceManager.GetString("DirectPayment_Model_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string DirectPayment_Model_Categoria {
            get {
                return ResourceManager.GetString("DirectPayment_Model_Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string DirectPayment_Model_Cliente {
            get {
                return ResourceManager.GetString("DirectPayment_Model_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string DirectPayment_Model_Company {
            get {
                return ResourceManager.GetString("DirectPayment_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string DirectPayment_Model_Date {
            get {
                return ResourceManager.GetString("DirectPayment_Model_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel Precio.
        /// </summary>
        public static string DirectPayment_Model_LevelPrice {
            get {
                return ResourceManager.GetString("DirectPayment_Model_LevelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota Cobro.
        /// </summary>
        public static string DirectPayment_Model_NotaCobro {
            get {
                return ResourceManager.GetString("DirectPayment_Model_NotaCobro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string DirectPayment_Model_Precio {
            get {
                return ResourceManager.GetString("DirectPayment_Model_Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesional.
        /// </summary>
        public static string DirectPayment_Model_Profesional {
            get {
                return ResourceManager.GetString("DirectPayment_Model_Profesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        public static string DirectPayment_Model_Rate {
            get {
                return ResourceManager.GetString("DirectPayment_Model_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio.
        /// </summary>
        public static string DirectPayment_Model_Servicio {
            get {
                return ResourceManager.GetString("DirectPayment_Model_Servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasa Profesional.
        /// </summary>
        public static string DirectPayment_Model_TasaProfesional {
            get {
                return ResourceManager.GetString("DirectPayment_Model_TasaProfesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string DirectPayment_Model_Total {
            get {
                return ResourceManager.GetString("DirectPayment_Model_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asistencia.
        /// </summary>
        public static string Event_Model_Asistencia {
            get {
                return ResourceManager.GetString("Event_Model_Asistencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Event_Model_Cliente {
            get {
                return ResourceManager.GetString("Event_Model_Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Event_Model_Color {
            get {
                return ResourceManager.GetString("Event_Model_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string Event_Model_Compania {
            get {
                return ResourceManager.GetString("Event_Model_Compania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Event_Model_DateStart {
            get {
                return ResourceManager.GetString("Event_Model_DateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string Event_Model_Description {
            get {
                return ResourceManager.GetString("Event_Model_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia Completo.
        /// </summary>
        public static string Event_Model_FullDay {
            get {
                return ResourceManager.GetString("Event_Model_FullDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        public static string Event_Model_Hora {
            get {
                return ResourceManager.GetString("Event_Model_Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo.
        /// </summary>
        public static string Event_Model_Motivo {
            get {
                return ResourceManager.GetString("Event_Model_Motivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesional.
        /// </summary>
        public static string Event_Model_Professional {
            get {
                return ResourceManager.GetString("Event_Model_Professional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string Event_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Event_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encabezado.
        /// </summary>
        public static string HeadText_IndexViewTitulo1 {
            get {
                return ResourceManager.GetString("HeadText_IndexViewTitulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string HeadText_Model_Compania {
            get {
                return ResourceManager.GetString("HeadText_Model_Compania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto Encabezado.
        /// </summary>
        public static string HeadText_Model_Texto {
            get {
                return ResourceManager.GetString("HeadText_Model_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orden.
        /// </summary>
        public static string Hora_Model_HoraOrden {
            get {
                return ResourceManager.GetString("Hora_Model_HoraOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        public static string Hora_Model_Horas {
            get {
                return ResourceManager.GetString("Hora_Model_Horas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Documento.
        /// </summary>
        public static string Identification_IndexView_Titulo1 {
            get {
                return ResourceManager.GetString("Identification_IndexView_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Identification_Model_Company {
            get {
                return ResourceManager.GetString("Identification_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Codumento.
        /// </summary>
        public static string Identification_Model_TipoDocumento {
            get {
                return ResourceManager.GetString("Identification_Model_TipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel Precio.
        /// </summary>
        public static string LevelPrice_Model_PriceLevel {
            get {
                return ResourceManager.GetString("LevelPrice_Model_PriceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel Precio.
        /// </summary>
        public static string LevelPrice_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("LevelPrice_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria Servicio.
        /// </summary>
        public static string Menu_Administracion_Category {
            get {
                return ResourceManager.GetString("Menu_Administracion_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta por Profesional.
        /// </summary>
        public static string Menu_Administracion_CxProfesional {
            get {
                return ResourceManager.GetString("Menu_Administracion_CxProfesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago Profesionales.
        /// </summary>
        public static string Menu_Administracion_LiquidarProfesionales {
            get {
                return ResourceManager.GetString("Menu_Administracion_LiquidarProfesionales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios.
        /// </summary>
        public static string Menu_Administracion_Service {
            get {
                return ResourceManager.GetString("Menu_Administracion_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobro Directo.
        /// </summary>
        public static string Menu_Adminitracion_CobroDirecto {
            get {
                return ResourceManager.GetString("Menu_Adminitracion_CobroDirecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string Menu_Agenda_Calendar {
            get {
                return ResourceManager.GetString("Menu_Agenda_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventos.
        /// </summary>
        public static string Menu_Agenda_Eventos {
            get {
                return ResourceManager.GetString("Menu_Agenda_Eventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string Menu_Archivo_Clients {
            get {
                return ResourceManager.GetString("Menu_Archivo_Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesionales.
        /// </summary>
        public static string Menu_Archivo_Profesional {
            get {
                return ResourceManager.GetString("Menu_Archivo_Profesional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string Menu_Link1 {
            get {
                return ResourceManager.GetString("Menu_Link1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio.
        /// </summary>
        public static string Menu_Link2 {
            get {
                return ResourceManager.GetString("Menu_Link2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprar.
        /// </summary>
        public static string Menu_Link3 {
            get {
                return ResourceManager.GetString("Menu_Link3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asistencia por Paciente.
        /// </summary>
        public static string Menu_Reportes_AsistenciaClientes {
            get {
                return ResourceManager.GetString("Menu_Reportes_AsistenciaClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asistencia General.
        /// </summary>
        public static string Menu_Reportes_AsistenciaGeneral {
            get {
                return ResourceManager.GetString("Menu_Reportes_AsistenciaGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecutivos.
        /// </summary>
        public static string Menu_Sistema_Consecutivos {
            get {
                return ResourceManager.GetString("Menu_Sistema_Consecutivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encabezado.
        /// </summary>
        public static string Menu_Sistema_Encabezado {
            get {
                return ResourceManager.GetString("Menu_Sistema_Encabezado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        public static string Menu_Sistema_Impuesto {
            get {
                return ResourceManager.GetString("Menu_Sistema_Impuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento Identidad.
        /// </summary>
        public static string Menu_Sistema_Indetificador {
            get {
                return ResourceManager.GetString("Menu_Sistema_Indetificador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Agenda de Citas, permite agendar la cita de multiples Profesionales en un solo sitio.  Podra disoner de una vista por Mes, Semana o por Dia.  Sus Profesionales podran verificar o agregar nuevas citas a sus agendas..
        /// </summary>
        public static string Menu_Text1 {
            get {
                return ResourceManager.GetString("Menu_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puedes crear servicios con 3 niveles de precios y agrupar estos servicios por Categorias.  Los profesionales podran hacer cobros por porcentajes de los servicos cobrados, demas de poder hacer los pagos a cada Profesional..
        /// </summary>
        public static string Menu_Text2 {
            get {
                return ResourceManager.GetString("Menu_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compra tu licencia por un Año, usando Mercadopago desde Colombia o desde Cualquier lugar con PayPal.  En los siguientes Links..
        /// </summary>
        public static string Menu_Text3 {
            get {
                return ResourceManager.GetString("Menu_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software de Agenda.
        /// </summary>
        public static string Menu_Titulo {
            get {
                return ResourceManager.GetString("Menu_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema de Acceso.
        /// </summary>
        public static string MenuAcceso {
            get {
                return ResourceManager.GetString("MenuAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egresos.
        /// </summary>
        public static string MenuAdmin_Egresos {
            get {
                return ResourceManager.GetString("MenuAdmin_Egresos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Usuario.
        /// </summary>
        public static string MenuLogin {
            get {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Sistema/Texto Encabezado, podra cambiar por la direccion, telefono y correo.
        /// </summary>
        public static string Msg_Compny_CreateHeadtext {
            get {
                return ResourceManager.GetString("Msg_Compny_CreateHeadtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe un Registro con el mismo Valor.
        /// </summary>
        public static string Msg_DoubleData {
            get {
                return ResourceManager.GetString("Msg_DoubleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Nombre o Apellido.
        /// </summary>
        public static string Msg_ErrorNameLastName {
            get {
                return ResourceManager.GetString("Msg_ErrorNameLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Campo {0} debe ser menor de {1} characters.
        /// </summary>
        public static string Msg_MaxLength {
            get {
                return ResourceManager.GetString("Msg_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Existen Registros para Continuar.
        /// </summary>
        public static string Msg_NoRegisterToContinue {
            get {
                return ResourceManager.GetString("Msg_NoRegisterToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe Seleccionar un Item.
        /// </summary>
        public static string Msg_Range {
            get {
                return ResourceManager.GetString("Msg_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Registo no puede ser Eliminado, porque tiene relacion con otros Datos.
        /// </summary>
        public static string Msg_Relationship {
            get {
                return ResourceManager.GetString("Msg_Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Campo {0} es Requerido.
        /// </summary>
        public static string Msg_Required {
            get {
                return ResourceManager.GetString("Msg_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desea Eliminar este Registro?.
        /// </summary>
        public static string MsgDelete {
            get {
                return ResourceManager.GetString("MsgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egresos.
        /// </summary>
        public static string Outcome_IndexView_Titulo1 {
            get {
                return ResourceManager.GetString("Outcome_IndexView_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Egresos.
        /// </summary>
        public static string Outcome_IndexView_Titulo12 {
            get {
                return ResourceManager.GetString("Outcome_IndexView_Titulo12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiario.
        /// </summary>
        public static string Outcome_Model_Beneficiario {
            get {
                return ResourceManager.GetString("Outcome_Model_Beneficiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string Outcome_Model_Company {
            get {
                return ResourceManager.GetString("Outcome_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Outcome_Model_Date {
            get {
                return ResourceManager.GetString("Outcome_Model_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string Outcome_Model_Detalle {
            get {
                return ResourceManager.GetString("Outcome_Model_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egreso.
        /// </summary>
        public static string Outcome_Model_Egreso {
            get {
                return ResourceManager.GetString("Outcome_Model_Egreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Egreso.
        /// </summary>
        public static string Outcome_Model_TotalValue {
            get {
                return ResourceManager.GetString("Outcome_Model_TotalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento.
        /// </summary>
        public static string OutcomeDetail_Model_Document {
            get {
                return ResourceManager.GetString("OutcomeDetail_Model_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto.
        /// </summary>
        public static string OutcomeDetail_Model_Valor {
            get {
                return ResourceManager.GetString("OutcomeDetail_Model_Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrado.
        /// </summary>
        public static string OutComes_Model_Close {
            get {
                return ResourceManager.GetString("OutComes_Model_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Items.
        /// </summary>
        public static string OutComes_Model_TotalValue {
            get {
                return ResourceManager.GetString("OutComes_Model_TotalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquidacion Profesionales.
        /// </summary>
        public static string PayProfessional_IndexView_Titulo1 {
            get {
                return ResourceManager.GetString("PayProfessional_IndexView_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string PayProfessional_Model_Company {
            get {
                return ResourceManager.GetString("PayProfessional_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string PayProfessional_Model_Date {
            get {
                return ResourceManager.GetString("PayProfessional_Model_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string PayProfessional_Model_Detalle {
            get {
                return ResourceManager.GetString("PayProfessional_Model_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota Pago.
        /// </summary>
        public static string PayProfessional_Model_NotaPago {
            get {
                return ResourceManager.GetString("PayProfessional_Model_NotaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago Profesional.
        /// </summary>
        public static string PayProfessional_Model_PagoProfessional {
            get {
                return ResourceManager.GetString("PayProfessional_Model_PagoProfessional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesional.
        /// </summary>
        public static string PayProfessional_Model_Professional {
            get {
                return ResourceManager.GetString("PayProfessional_Model_Professional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string PrintViewData_Model_Company {
            get {
                return ResourceManager.GetString("PrintViewData_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde.
        /// </summary>
        public static string PrintViewData_Model_FechaDesde {
            get {
                return ResourceManager.GetString("PrintViewData_Model_FechaDesde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta.
        /// </summary>
        public static string PrintViewData_Model_FechaHasta {
            get {
                return ResourceManager.GetString("PrintViewData_Model_FechaHasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesional.
        /// </summary>
        public static string Profe_IndexView_Titulo1 {
            get {
                return ResourceManager.GetString("Profe_IndexView_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Profe_Model_Active {
            get {
                return ResourceManager.GetString("Profe_Model_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion.
        /// </summary>
        public static string Profe_Model_Address {
            get {
                return ResourceManager.GetString("Profe_Model_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string Profe_Model_Compania {
            get {
                return ResourceManager.GetString("Profe_Model_Compania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombres.
        /// </summary>
        public static string Profe_Model_FirstName {
            get {
                return ResourceManager.GetString("Profe_Model_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profesional.
        /// </summary>
        public static string Profe_Model_FullName {
            get {
                return ResourceManager.GetString("Profe_Model_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos.
        /// </summary>
        public static string Profe_Model_LastName {
            get {
                return ResourceManager.GetString("Profe_Model_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movil.
        /// </summary>
        public static string Profe_Model_Movil {
            get {
                return ResourceManager.GetString("Profe_Model_Movil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero Documento.
        /// </summary>
        public static string Profe_Model_NumberDocu {
            get {
                return ResourceManager.GetString("Profe_Model_NumberDocu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string Profe_Model_Phone {
            get {
                return ResourceManager.GetString("Profe_Model_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        public static string Profe_Model_Photo {
            get {
                return ResourceManager.GetString("Profe_Model_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentaje.
        /// </summary>
        public static string Profe_Model_Porcent {
            get {
                return ResourceManager.GetString("Profe_Model_Porcent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Documento.
        /// </summary>
        public static string Profe_Model_TypeDocu {
            get {
                return ResourceManager.GetString("Profe_Model_TypeDocu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string Profe_Model_UserName {
            get {
                return ResourceManager.GetString("Profe_Model_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota Cobro.
        /// </summary>
        public static string Register_Model_BillingNote {
            get {
                return ResourceManager.GetString("Register_Model_BillingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprobante Pago.
        /// </summary>
        public static string Register_Model_ComprobantePago {
            get {
                return ResourceManager.GetString("Register_Model_ComprobantePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egresos.
        /// </summary>
        public static string Register_Model_Expenses {
            get {
                return ResourceManager.GetString("Register_Model_Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consecutivo.
        /// </summary>
        public static string Register_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("Register_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios.
        /// </summary>
        public static string Service_IndexView_Titulo1 {
            get {
                return ResourceManager.GetString("Service_IndexView_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string Service_Model_Categoria {
            get {
                return ResourceManager.GetString("Service_Model_Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string Service_Model_Compania {
            get {
                return ResourceManager.GetString("Service_Model_Compania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string Service_Model_Detalle {
            get {
                return ResourceManager.GetString("Service_Model_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        public static string Service_Model_Impuesto {
            get {
                return ResourceManager.GetString("Service_Model_Impuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio 1.
        /// </summary>
        public static string Service_Model_Precio1 {
            get {
                return ResourceManager.GetString("Service_Model_Precio1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio 2.
        /// </summary>
        public static string Service_Model_Precio2 {
            get {
                return ResourceManager.GetString("Service_Model_Precio2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio 3.
        /// </summary>
        public static string Service_Model_Precio3 {
            get {
                return ResourceManager.GetString("Service_Model_Precio3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio.
        /// </summary>
        public static string Service_Model_Servicio {
            get {
                return ResourceManager.GetString("Service_Model_Servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        public static string ServiceCategory_Model_Categoria {
            get {
                return ResourceManager.GetString("ServiceCategory_Model_Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string ServiceCategory_Model_Company {
            get {
                return ResourceManager.GetString("ServiceCategory_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria Servicio.
        /// </summary>
        public static string ServiceCategory_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("ServiceCategory_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string ServiceCateogory_Model_Detail {
            get {
                return ResourceManager.GetString("ServiceCateogory_Model_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        public static string Tax_IndexView_Titulo1 {
            get {
                return ResourceManager.GetString("Tax_IndexView_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compania.
        /// </summary>
        public static string Tax_Model_Company {
            get {
                return ResourceManager.GetString("Tax_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        public static string Tax_Model_Impuesto {
            get {
                return ResourceManager.GetString("Tax_Model_Impuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasa.
        /// </summary>
        public static string Tax_Model_Tasa {
            get {
                return ResourceManager.GetString("Tax_Model_Tasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direccion.
        /// </summary>
        public static string User_Model_Address {
            get {
                return ResourceManager.GetString("User_Model_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañia.
        /// </summary>
        public static string User_Model_Company {
            get {
                return ResourceManager.GetString("User_Model_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string User_Model_Email {
            get {
                return ResourceManager.GetString("User_Model_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string User_Model_FisrtName {
            get {
                return ResourceManager.GetString("User_Model_FisrtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string User_Model_FullName {
            get {
                return ResourceManager.GetString("User_Model_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string User_Model_LastName {
            get {
                return ResourceManager.GetString("User_Model_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string User_Model_Phone {
            get {
                return ResourceManager.GetString("User_Model_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        public static string User_Model_Photo {
            get {
                return ResourceManager.GetString("User_Model_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puesto.
        /// </summary>
        public static string User_Model_Puesto {
            get {
                return ResourceManager.GetString("User_Model_Puesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string User_ViewIndex_Titulo1 {
            get {
                return ResourceManager.GetString("User_ViewIndex_Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string ViewCreate {
            get {
                return ResourceManager.GetString("ViewCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        public static string ViewDelete {
            get {
                return ResourceManager.GetString("ViewDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        public static string ViewDetail {
            get {
                return ResourceManager.GetString("ViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string ViewEdit {
            get {
                return ResourceManager.GetString("ViewEdit", resourceCulture);
            }
        }
    }
}
